<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>Apos.Input.KNI</PackageId>
    <Title>Apos.Input.KNI</Title>
    <Description>Input library for KNI.</Description>
    <Authors>Jean-David Moisan</Authors>
    <Company>Vyne Enterprise Inc.</Company>
    <Copyright>Copyright 2026</Copyright>
    <PackageTags>gamedev;monogame;input</PackageTags>
    <PackageIcon>Icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/Apostolique/Apos.Input</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Apostolique/Apos.Input</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryType>git</RepositoryType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nkast.Xna.Framework" Version="4.2.9001" />
    <PackageReference Include="nkast.Xna.Framework.Game" Version="4.2.9001" />
    <PackageReference Include="nkast.Xna.Framework.Input" Version="4.2.9001" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../Images/Icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <SourceRoot Include="$(MSBuildThisFileDirectory)/"/>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

</Project>
