name: Build and test

on:
  push:
    branches:
    - 'main'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Build
      run: |
        dotnet build Source/Apos.Input.csproj -c Release
        dotnet build Source/Apos.Input.KNI.csproj -c Release
    - name: Test
      run: dotnet test Tests/Apos.Input.Tests.csproj -c Release
